### ISSUE TITLE
d3 Not Defined

### ISSUE THREAD

**Issue by ghost** [ConnectedMachines/TesselDrone#66]
Issue with tesseldrone.cloudapp.net - apparently d3 is no longer defined. Haven't encountered this issue yet, probably time to check to make sure if all dependencies are being installed.

**Comment by ghost** [comment]
Closing issue - seemed to have been resolved. Perhaps an issue with using a CDN. We can look at later.

**Comment by mLuby** [comment]
Thanks for quick resolution.
