### ISSUE TITLE
Assets not loading properly for 3D model and 2 logos post server reset

### ISSUE THREAD

**Issue by ghost** [ConnectedMachines/TesselDrone#68]

**Comment by mLuby** [comment]
Failed to load resource: the server responded with a status of 404 (Not Found) http://tesseldrone.cloudapp.net/client/assets/tesselBoard_board.stl

Failed to load resource: the server responded with a status of 404 (Not Found) http://tesseldrone.cloudapp.net/client/assets/tesselBoard_deco.stl

**Comment by mLuby** [comment]
Issue is most likely that those two file names are _not_ camel-cased.

**Comment by Zithrill** [comment]
ya this was a local change that we made on the spot before but didn't commit if you look at one of the closed issues its almost identical and has the fix in the comment

**Comment by mLuby** [comment]
[PR #69](https://github.com/ConnectedMachines/TesselDrone/pull/69) should fix it.

**Comment by ghost** [comment]
Waiting for Travis : D
